package decoder

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/Eyevinn/mp4ff/avc"
)

// goldenTests maps test name to expected SHA-256 of decoded YUV output.
// Generated by tools/update_golden.sh — do not edit manually.
var goldenTests = map[string]string{
	"aq_autovar_strong":  "4a3bf5051a517275dcc5bdc07676c9b8428d941fee64adc1131ae40935b7e1a4",
	"aq_variance":        "c348bc4af987df4d48ffa72921bdadba424efd2d613188cbd74a0566aefa5225",
	"constrained_intra":  "c348bc4af987df4d48ffa72921bdadba424efd2d613188cbd74a0566aefa5225",
	"content_black":      "c085db002b8801e7c88b33dd5b50d8a8052d33d1bb77937998c75d9fc064f7de",
	"content_mandelbrot": "dfcdc99e2c776d190eee201dc011f8120a6af34f9f5b1a8a8d3eadb9a6f8054b",
	"content_red":        "89b5fe971e097db2c37b2809c9b4f2e77a3137c3de4c774b5b51eeb434f3291f",
	"content_smptebars":  "f9a9b7d16d0cf7dcd144c14fab5602627e3d05a58c0cadabb4371cd5bcb7789d",
	"content_testsrc2":   "c348bc4af987df4d48ffa72921bdadba424efd2d613188cbd74a0566aefa5225",
	"cqm_jvt":            "f89be60311138d1b43c2a4413d8032e90397780c67be2c1e94bb377a7d159070",
	"cqp_offset_neg4":    "5189e431a887493c67a0f38f66d6423fe5634df0e4e5492404e724ee944b6968",
	"cqp_offset_pos4":    "d8b822b7e59830d5df7c4078ead0327fc8c545389168c4ea37fca97aa6024532",
	"deblock_neg":        "43b4d3094b7bd6f08459841e45a70bb44a6fdc4ca2a46a3e6fb7159ef6ffbe59",
	"deblock_off":        "69af2a5e4b5cf24fea88e2fd0d5dec7d942c12d27e6fe81cb16bba71669cb47a",
	"deblock_strong":     "2a7d59f5e016c244b6c918d6d1550ce6465ebd6ec9f3503bbc1ccc2196df5717",
	"dz_max":             "bf259568c42bba80513f7ec16d998afb1b4a378af497b16ed717934b30284aff",
	"dz_min":             "cc09cc2a58c263f53b72263d9e59e09ca77ab614a202e2202982da4d1d186f6a",
	"no_dct_dec":         "c348bc4af987df4d48ffa72921bdadba424efd2d613188cbd74a0566aefa5225",
	"no_psy":             "61213d022ca0513deda7e9f161c072a8b5b6fb488d317a72c5ca5653752c093e",
	"part_i4x4_only":     "d489d221081694b5066c2486ad3e7cf7cec937c406bede95749af6877007665b",
	"part_none":          "c348bc4af987df4d48ffa72921bdadba424efd2d613188cbd74a0566aefa5225",
	"profile_main":       "d489d221081694b5066c2486ad3e7cf7cec937c406bede95749af6877007665b",
	"qp10":               "6c8ba671c0be5dd231780328dd7145adb17c7dcabb854cd81d0009ad85b5f65c",
	"qp40":               "720da78c8b9ffd6f6c7fa8795f02e143cea0bfd3881edf30ee76115d53620cf9",
	"qp51":               "c120ca9885e5824edfd24b8183d17049782a0d8b458591aeff5ee02aa15c63a8",
	"res_hd":             "ff9e55b5b27c84350106385e407b39d2c0dea81002b6672c8655a1ee2280ac69",
	"res_qcif":           "d0e1a0ac7f867b16dc8f32e7386b296939c04488c74fefd7785d0b8d4422e077",
	"res_tiny":           "c1dd0eb80a4347ec684a2d7e2ca813cffffe192ad5527b873d6a359bb83ae85e",
	"res_wide":           "991b3c49a62271d0471b7a93e9a69ce075604df64080649ea4722e5a73a8bb27",
	"subme1":             "1961a873278a6c9cb90110fba744078c94a8668412300811828c890fda59a85e",
	"subme11":            "00f48eec8caa2e05952ecf8a4943fbcacd2924acb07cea8b1914a5968a1c9acf",
	"trellis0":           "07d08fb51da1e514dd718001c76e457511225388e35b3d6b13aa24461c4f0ec7",
	"trellis2":           "ed935fe6b4ed6ab5ac74993e348f205a18997120ca2552858d094e95d9648e74",
	// CAVLC (entropy_coding_mode_flag=0) golden tests
	"cavlc_baseline": "c3e608f1e377c156b0adb72f381ac7256a703bcb3d9a4c04b7dfa1054a92f828",
	"cavlc_black":    "c085db002b8801e7c88b33dd5b50d8a8052d33d1bb77937998c75d9fc064f7de",
	"cavlc_cqm":      "c46ccae2fc1eaa0c55bc238d69e8f2a5d9c33a98c535236aff0b964de253c466",
	"cavlc_hd":       "76bbcacd2dfb629097f00d625d3954aa9ba4292d71794600a1146adfaa6a6659",
	"cavlc_high":     "5c9a3443646b73dffa479a002815c050e39f93593ff0bdf37383ae3bef2f632f",
	"cavlc_main":     "c3e608f1e377c156b0adb72f381ac7256a703bcb3d9a4c04b7dfa1054a92f828",
	"cavlc_qp10":     "a90eb388182e100acc685692c27e4359a8406fdf73e3bcb2198517fb80809f25",
	"cavlc_qp40":     "fd52639a04bcd156521fe1fb4415ececf299b826b064b7efa283bdbea0a012b9",
	"cavlc_tiny":     "e8540d96643d61ffa28bbd7409933f937e4c9d5b5a1ab51b0bfc5db72123a8a9",
}

func TestGoldenDecode(t *testing.T) {
	goldenDir := filepath.Join("..", "..", "testdata", "golden")

	for name, wantHash := range goldenTests {
		t.Run(name, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join(goldenDir, name+".264"))
			if err != nil {
				t.Fatalf("read input: %v", err)
			}

			nalus := avc.ExtractNalusFromByteStream(data)
			dec := New()
			frame, err := dec.DecodeNALUs(nalus)
			if err != nil {
				t.Fatalf("decode: %v", err)
			}

			yuv := frame.YUV420Bytes()
			gotHash := fmt.Sprintf("%x", sha256.Sum256(yuv))
			if gotHash != wantHash {
				t.Errorf("SHA-256 mismatch\n  got:  %s\n  want: %s", gotHash, wantHash)
			}
		})
	}
}
