package encode

import (
	"bytes"
	"strings"
	"testing"

	"github.com/Eyevinn/mp4ff/avc"

	"github.com/Eyevinn/hi264/pkg/decoder"
	"github.com/Eyevinn/hi264/pkg/frame"
	"github.com/Eyevinn/hi264/pkg/yuv"
)

// buildSourceStream returns SPS + PPS + IDR for a small two-colour pattern.
func buildSourceStream(t *testing.T, cabac bool) []byte {
	t.Helper()
	grid, err := yuv.ParseGrid("xy,yx")
	if err != nil {
		t.Fatal(err)
	}
	colors := yuv.ColorMap{
		'x': {Y: 200, Cb: 100, Cr: 150},
		'y': {Y: 50, Cb: 200, Cr: 80},
	}
	enc := &FrameEncoder{
		Grid: grid, Colors: colors, QP: 26, DisableDeblock: 1, MaxNumRefFrames: 1, CABAC: cabac,
	}
	var buf bytes.Buffer
	if err := enc.EncodeSPSPPS(&buf); err != nil {
		t.Fatalf("EncodeSPSPPS: %v", err)
	}
	idr, err := enc.EncodeSlice(0)
	if err != nil {
		t.Fatalf("EncodeSlice: %v", err)
	}
	buf.Write(idr)
	return buf.Bytes()
}

func decodeAll(t *testing.T, annexB []byte) []*frame.Frame {
	t.Helper()
	dec := decoder.New()
	dec.SkipDeblock = true
	frames, err := dec.DecodeAllFrames(avc.ExtractNalusFromByteStream(annexB))
	if err != nil {
		t.Fatalf("DecodeAllFrames: %v", err)
	}
	return frames
}

func requireSamePicture(t *testing.T, got, want *frame.Frame, what string) {
	t.Helper()
	if !bytes.Equal(got.Y, want.Y) || !bytes.Equal(got.Cb, want.Cb) || !bytes.Equal(got.Cr, want.Cr) {
		t.Fatalf("%s differs from the reference picture", what)
	}
}

// TestPSkipExtenderFreezesStream checks the core promise: frames generated by a PSkipExtender continue the
// source and decode as a freeze of its last picture, for both entropy coders.
func TestPSkipExtenderFreezesStream(t *testing.T) {
	for _, tc := range []struct {
		name  string
		cabac bool
	}{
		{"CAVLC", false},
		{"CABAC", true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			source := buildSourceStream(t, tc.cabac)
			sps, pps := mustParseSPSPPS(t, source)
			ext, err := NewPSkipExtender(sps, pps)
			if err != nil {
				t.Fatalf("NewPSkipExtender: %v", err)
			}
			if ext.Ready() {
				t.Fatal("Ready before observing anything")
			}
			if err := ext.ObserveAnnexB(source); err != nil {
				t.Fatalf("ObserveAnnexB: %v", err)
			}
			if !ext.Ready() {
				t.Fatal("not ready after observing an IDR")
			}
			if fn, poc := ext.State(); fn != 0 || poc != 0 {
				t.Fatalf("State after IDR = (%d, %d), want (0, 0)", fn, poc)
			}

			const n = 5
			slices, err := ext.NextSlices(n)
			if err != nil {
				t.Fatalf("NextSlices: %v", err)
			}
			if len(slices) != n {
				t.Fatalf("got %d slices, want %d", len(slices), n)
			}
			if ext.Generated() != n {
				t.Fatalf("Generated = %d, want %d", ext.Generated(), n)
			}

			extended := append([]byte(nil), source...)
			for _, s := range slices {
				extended = append(extended, s...)
			}
			frames := decodeAll(t, extended)
			if len(frames) != n+1 {
				t.Fatalf("decoded %d frames, want %d", len(frames), n+1)
			}
			for i := 1; i <= n; i++ {
				requireSamePicture(t, frames[i], frames[0], "generated frame")
			}

			// the numbering continued as expected
			if fn, poc := ext.State(); fn != n || poc != 2*n {
				t.Fatalf("State = (%d, %d), want (%d, %d)", fn, poc, n, 2*n)
			}
		})
	}
}

// TestPSkipExtenderMatchesAppendPSkipFrames pins the new API to the existing one for the simple case
// both handle: a stream in which every picture is a reference picture.
func TestPSkipExtenderMatchesAppendPSkipFrames(t *testing.T) {
	source := buildSourceStream(t, false)
	want, err := AppendPSkipFrames(source, 4)
	if err != nil {
		t.Fatalf("AppendPSkipFrames: %v", err)
	}

	sps, pps := mustParseSPSPPS(t, source)
	ext, err := NewPSkipExtender(sps, pps)
	if err != nil {
		t.Fatalf("NewPSkipExtender: %v", err)
	}
	if err := ext.ObserveAnnexB(source); err != nil {
		t.Fatalf("ObserveAnnexB: %v", err)
	}
	slices, err := ext.NextSlices(4)
	if err != nil {
		t.Fatalf("NextSlices: %v", err)
	}
	got := append([]byte(nil), source...)
	for _, s := range slices {
		got = append(got, s...)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("PSkipExtender output differs from AppendPSkipFrames (%d vs %d bytes)", len(got), len(want))
	}
}

// TestPSkipExtenderObservesAVCCSample covers the fragmented-MP4 and RTMP input shape.
func TestPSkipExtenderObservesAVCCSample(t *testing.T) {
	source := buildSourceStream(t, false)
	sps, pps := mustParseSPSPPS(t, source)
	ext, err := NewPSkipExtender(sps, pps)
	if err != nil {
		t.Fatalf("NewPSkipExtender: %v", err)
	}
	// the IDR alone, as a length-prefixed sample without in-band parameter sets
	var idr []byte
	for _, nalu := range avc.ExtractNalusFromByteStream(source) {
		if avc.GetNaluType(nalu[0]) == avc.NALU_IDR {
			idr = nalu
		}
	}
	if idr == nil {
		t.Fatal("no IDR in source")
	}
	sample := make([]byte, 0, len(idr)+4)
	sample = append(sample, byte(len(idr)>>24), byte(len(idr)>>16), byte(len(idr)>>8), byte(len(idr)))
	sample = append(sample, idr...)
	if err := ext.ObserveAVCCSample(sample); err != nil {
		t.Fatalf("ObserveAVCCSample: %v", err)
	}
	if !ext.Ready() {
		t.Fatal("not ready after observing an AVCC sample")
	}
	if _, err := ext.NextSlice(); err != nil {
		t.Fatalf("NextSlice: %v", err)
	}
}

// TestPSkipExtenderFromDecConfRec covers construction from an avcC record.
func TestPSkipExtenderFromDecConfRec(t *testing.T) {
	source := buildSourceStream(t, false)
	var spsNalus, ppsNalus [][]byte
	for _, nalu := range avc.ExtractNalusFromByteStream(source) {
		switch avc.GetNaluType(nalu[0]) {
		case avc.NALU_SPS:
			spsNalus = append(spsNalus, nalu)
		case avc.NALU_PPS:
			ppsNalus = append(ppsNalus, nalu)
		}
	}
	rec, err := avc.CreateAVCDecConfRec(spsNalus, ppsNalus, true)
	if err != nil {
		t.Fatalf("CreateAVCDecConfRec: %v", err)
	}
	var buf bytes.Buffer
	if err := rec.Encode(&buf); err != nil {
		t.Fatalf("encode avcC: %v", err)
	}
	ext, err := NewPSkipExtenderFromDecConfRec(buf.Bytes())
	if err != nil {
		t.Fatalf("NewPSkipExtenderFromDecConfRec: %v", err)
	}
	if err := ext.ObserveAnnexB(source); err != nil {
		t.Fatalf("ObserveAnnexB: %v", err)
	}
	slices, err := ext.NextSlices(2)
	if err != nil {
		t.Fatalf("NextSlices: %v", err)
	}
	extended := append([]byte(nil), source...)
	for _, s := range slices {
		extended = append(extended, s...)
	}
	if frames := decodeAll(t, extended); len(frames) != 3 {
		t.Fatalf("decoded %d frames, want 3", len(frames))
	}
}

// TestPSkipExtenderIDRResetsState checks that an IDR discards the numbering that preceded it, which is
// how a stream resumes after frames have been inserted.
func TestPSkipExtenderIDRResetsState(t *testing.T) {
	source := buildSourceStream(t, false)
	sps, pps := mustParseSPSPPS(t, source)
	ext, err := NewPSkipExtender(sps, pps)
	if err != nil {
		t.Fatalf("NewPSkipExtender: %v", err)
	}
	if err := ext.ObserveAnnexB(source); err != nil {
		t.Fatalf("ObserveAnnexB: %v", err)
	}
	if _, err := ext.NextSlices(3); err != nil {
		t.Fatalf("NextSlices: %v", err)
	}
	if fn, poc := ext.State(); fn != 3 || poc != 6 {
		t.Fatalf("State after filling = (%d, %d), want (3, 6)", fn, poc)
	}
	// real video resumes with a fresh IDR
	if err := ext.ObserveAnnexB(source); err != nil {
		t.Fatalf("ObserveAnnexB: %v", err)
	}
	if fn, poc := ext.State(); fn != 0 || poc != 0 {
		t.Fatalf("State after the resuming IDR = (%d, %d), want (0, 0)", fn, poc)
	}
}

// TestPSkipExtenderWrapsNumbering generates more frames than the SPS numbering allows, so both
// frame_num and the picture order count wrap, and checks the stream still decodes.
func TestPSkipExtenderWrapsNumbering(t *testing.T) {
	source := buildSourceStream(t, false)
	sps, pps := mustParseSPSPPS(t, source)
	maxFrameNum := uint32(1) << (sps.Log2MaxFrameNumMinus4 + 4)
	maxPOC := uint32(1) << (sps.Log2MaxPicOrderCntLsbMinus4 + 4)

	ext, err := NewPSkipExtender(sps, pps)
	if err != nil {
		t.Fatalf("NewPSkipExtender: %v", err)
	}
	if err := ext.ObserveAnnexB(source); err != nil {
		t.Fatalf("ObserveAnnexB: %v", err)
	}
	n := int(maxFrameNum) + int(maxPOC) + 3 // past both wraps
	slices, err := ext.NextSlices(n)
	if err != nil {
		t.Fatalf("NextSlices: %v", err)
	}
	fn, poc := ext.State()
	if fn >= maxFrameNum {
		t.Fatalf("frame_num %d did not wrap (max %d)", fn, maxFrameNum)
	}
	if poc >= maxPOC {
		t.Fatalf("pic_order_cnt_lsb %d did not wrap (max %d)", poc, maxPOC)
	}
	if want := uint32(n) % maxFrameNum; fn != want {
		t.Fatalf("frame_num = %d, want %d", fn, want)
	}
	if want := (uint32(n) * 2) % maxPOC; poc != want {
		t.Fatalf("pic_order_cnt_lsb = %d, want %d", poc, want)
	}

	extended := append([]byte(nil), source...)
	for _, s := range slices {
		extended = append(extended, s...)
	}
	frames := decodeAll(t, extended)
	if len(frames) != n+1 {
		t.Fatalf("decoded %d frames, want %d", len(frames), n+1)
	}
	requireSamePicture(t, frames[len(frames)-1], frames[0], "last generated frame")
}

// nextSliceHeader generates one slice and parses its header back, so the test asserts on the bits
// that were written rather than on internal state.
func nextSliceHeader(t *testing.T, ext *PSkipExtender) *avc.SliceHeader {
	t.Helper()
	annexB, err := ext.NextSlice()
	if err != nil {
		t.Fatalf("NextSlice: %v", err)
	}
	nalus := avc.ExtractNalusFromByteStream(annexB)
	if len(nalus) != 1 {
		t.Fatalf("expected one NAL unit, got %d", len(nalus))
	}
	sh, err := avc.ParseSliceHeader(nalus[0], ext.spsMap, ext.ppsMap)
	if err != nil {
		t.Fatalf("ParseSliceHeader: %v", err)
	}
	return sh
}

// TestPSkipExtenderFollowsReferenceStructure covers the two rules that separate this from continuing
// straight off the last coded slice. They only differ on streams containing B frames, where the
// last picture in decode order is neither necessarily a reference picture nor the latest in display
// order. hi264 cannot generate such a stream, so the pictures are fed in directly.
func TestPSkipExtenderFollowsReferenceStructure(t *testing.T) {
	source := buildSourceStream(t, false)
	sps, pps := mustParseSPSPPS(t, source)

	newExt := func(t *testing.T) *PSkipExtender {
		t.Helper()
		ext, err := NewPSkipExtender(sps, pps)
		if err != nil {
			t.Fatalf("NewPSkipExtender: %v", err)
		}
		if err := ext.ObserveAnnexB(source); err != nil {
			t.Fatalf("ObserveAnnexB: %v", err)
		}
		return ext
	}

	t.Run("a trailing non-reference picture does not advance frame_num", func(t *testing.T) {
		// IDR(0, 0) from the source, then P(frame_num 1, poc 4) and a non-reference B(frame_num 2,
		// poc 2): a live stream cut mid-reorder ends exactly like this. The next reference picture
		// is frame_num 2, not 3, because frame_num counts reference pictures and the B already
		// shares the value the next one takes. Continuing off the last coded slice would give
		// (3, 4) instead of (2, 6).
		ext := newExt(t)
		ext.observeSlice(&avc.SliceHeader{FrameNum: 1, PicOrderCntLsb: 4}, false, true)
		ext.observeSlice(&avc.SliceHeader{FrameNum: 2, PicOrderCntLsb: 2}, false, false)
		if fn, poc := ext.State(); fn != 1 || poc != 4 {
			t.Fatalf("State = (%d, %d), want (1, 4)", fn, poc)
		}
		sh := nextSliceHeader(t, ext)
		if sh.FrameNum != 2 {
			t.Errorf("frame_num = %d, want 2 (continuing the last reference picture)", sh.FrameNum)
		}
		if sh.PicOrderCntLsb != 6 {
			t.Errorf("pic_order_cnt_lsb = %d, want 6 (continuing the highest value)", sh.PicOrderCntLsb)
		}
	})

	t.Run("the picture order count continues from the highest value", func(t *testing.T) {
		// A reordered reference picture can itself carry a lower count than one already coded.
		ext := newExt(t)
		ext.observeSlice(&avc.SliceHeader{FrameNum: 1, PicOrderCntLsb: 6}, false, true)
		ext.observeSlice(&avc.SliceHeader{FrameNum: 2, PicOrderCntLsb: 2}, false, true)
		if sh := nextSliceHeader(t, ext); sh.PicOrderCntLsb != 8 {
			t.Errorf("pic_order_cnt_lsb = %d, want 8", sh.PicOrderCntLsb)
		}
	})

	t.Run("an IDR discards what came before it", func(t *testing.T) {
		ext := newExt(t)
		ext.observeSlice(&avc.SliceHeader{FrameNum: 1, PicOrderCntLsb: 6}, false, true)
		ext.observeSlice(&avc.SliceHeader{FrameNum: 0, PicOrderCntLsb: 0}, true, true)
		sh := nextSliceHeader(t, ext)
		if sh.FrameNum != 1 || sh.PicOrderCntLsb != 2 {
			t.Errorf("after an IDR: (%d, %d), want (1, 2)", sh.FrameNum, sh.PicOrderCntLsb)
		}
	})
}

// pSkipNALU returns a reference P_Skip slice as a NAL unit without start code.
func pSkipNALU(t *testing.T, sps *avc.SPS, pps *avc.PPS, frameNum, pocLsb uint32) []byte {
	t.Helper()
	annexB, err := EncodePSkipSlice(sps, pps, frameNum, pocLsb, 1)
	if err != nil {
		t.Fatalf("EncodePSkipSlice: %v", err)
	}
	return avc.ExtractNalusFromByteStream(annexB)[0]
}

// TestPSkipExtenderJoinsMidStream covers a live pipeline that starts observing between IDRs: the
// first slice it sees is a P slice, and the numbering continues from it.
func TestPSkipExtenderJoinsMidStream(t *testing.T) {
	sps, pps := mustParseSPSPPS(t, buildSourceStream(t, false))
	ext, err := NewPSkipExtender(sps, pps)
	if err != nil {
		t.Fatalf("NewPSkipExtender: %v", err)
	}
	if err := ext.ObserveNALU(pSkipNALU(t, sps, pps, 5, 10)); err != nil {
		t.Fatalf("ObserveNALU: %v", err)
	}
	if fn, poc := ext.State(); !ext.Ready() || fn != 5 || poc != 10 {
		t.Fatalf("Ready = %v, State = (%d, %d), want true, (5, 10)", ext.Ready(), fn, poc)
	}
	if sh := nextSliceHeader(t, ext); sh.FrameNum != 6 || sh.PicOrderCntLsb != 12 {
		t.Errorf("next slice (%d, %d), want (6, 12)", sh.FrameNum, sh.PicOrderCntLsb)
	}
}

// TestPSkipExtenderDamagedInput checks that a NAL unit that does not parse is reported and leaves
// the numbering unchanged, so a caller can drop a damaged access unit and keep observing.
func TestPSkipExtenderDamagedInput(t *testing.T) {
	source := buildSourceStream(t, false)
	sps, pps := mustParseSPSPPS(t, source)
	ext, err := NewPSkipExtender(sps, pps)
	if err != nil {
		t.Fatalf("NewPSkipExtender: %v", err)
	}
	if err := ext.ObserveAnnexB(source); err != nil {
		t.Fatalf("ObserveAnnexB: %v", err)
	}
	if err := ext.ObserveNALU(pSkipNALU(t, sps, pps, 1, 2)); err != nil {
		t.Fatalf("ObserveNALU: %v", err)
	}

	var spsNALU, ppsNALU []byte
	for _, nalu := range avc.ExtractNalusFromByteStream(source) {
		switch avc.GetNaluType(nalu[0]) {
		case avc.NALU_SPS:
			spsNALU = nalu
		case avc.NALU_PPS:
			ppsNALU = nalu
		}
	}
	truncatedSlice := pSkipNALU(t, sps, pps, 2, 4)[:2]
	cases := []struct {
		name    string
		observe func() error
		wantErr string
	}{
		{"truncated slice", func() error { return ext.ObserveNALU(truncatedSlice) }, "parse slice header"},
		{"truncated slice in Annex-B", func() error {
			return ext.ObserveAnnexB(append([]byte{0, 0, 0, 1}, truncatedSlice...))
		}, "parse slice header"},
		{"bad AVCC length", func() error { return ext.ObserveAVCCSample([]byte{0, 0, 0, 9, 0x41}) },
			"split access unit"},
		{"truncated slice in AVCC sample", func() error {
			return ext.ObserveAVCCSample(append([]byte{0, 0, 0, byte(len(truncatedSlice))}, truncatedSlice...))
		}, "parse slice header"},
		{"truncated SPS", func() error { return ext.ObserveNALU(spsNALU[:3]) }, "parse SPS"},
		{"truncated PPS", func() error { return ext.ObserveNALU(ppsNALU[:1]) }, "parse PPS"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			err := c.observe()
			if err == nil || !strings.Contains(err.Error(), c.wantErr) {
				t.Fatalf("got error %v, want one containing %q", err, c.wantErr)
			}
			if fn, poc := ext.State(); fn != 1 || poc != 2 {
				t.Errorf("State = (%d, %d) after the error, want (1, 2)", fn, poc)
			}
		})
	}

	if err := ext.ObserveNALU(nil); err != nil {
		t.Errorf("an empty NAL unit: %v", err)
	}
	if err := ext.ObserveNALU(pSkipNALU(t, sps, pps, 2, 4)); err != nil {
		t.Fatalf("ObserveNALU after the damaged units: %v", err)
	}
	if fn, poc := ext.State(); fn != 2 || poc != 4 {
		t.Errorf("State = (%d, %d), want (2, 4)", fn, poc)
	}
}

func TestPSkipExtenderErrors(t *testing.T) {
	source := buildSourceStream(t, false)
	sps, pps := mustParseSPSPPS(t, source)

	if _, err := NewPSkipExtender(nil, pps); err == nil {
		t.Error("NewPSkipExtender(nil, pps) should fail")
	}
	if _, err := NewPSkipExtender(sps, nil); err == nil {
		t.Error("NewPSkipExtender(sps, nil) should fail")
	}

	poc1 := *sps
	poc1.PicOrderCntType = 1
	if _, err := NewPSkipExtender(&poc1, pps); err == nil {
		t.Error("pic_order_cnt_type=1 should be rejected")
	}

	interlaced := *sps
	interlaced.FrameMbsOnlyFlag = false
	if _, err := NewPSkipExtender(&interlaced, pps); err == nil {
		t.Error("interlaced should be rejected")
	}

	ext, err := NewPSkipExtender(sps, pps)
	if err != nil {
		t.Fatalf("NewPSkipExtender: %v", err)
	}
	if _, err := ext.NextSlice(); err == nil {
		t.Error("NextSlice before observing a slice should fail")
	}
	if slices, err := ext.NextSlices(0); err != nil || slices != nil {
		t.Errorf("NextSlices(0) = (%v, %v), want (nil, nil)", slices, err)
	}
	if _, err := NewPSkipExtenderFromDecConfRec([]byte{2, 0, 0, 0}); err == nil {
		t.Error("a malformed avcC should be rejected")
	}
}

func TestPocIsLater(t *testing.T) {
	const max = 16
	for _, tc := range []struct {
		a, b uint32
		want bool
	}{
		{4, 2, true},
		{2, 4, false},
		{2, 2, false},
		{0, 14, true},  // wrapped forward
		{14, 0, false}, // the same pair seen the other way round
		{8, 0, true},   // exactly half a cycle ahead
	} {
		if got := pocIsLater(tc.a, tc.b, max); got != tc.want {
			t.Errorf("pocIsLater(%d, %d, %d) = %v, want %v", tc.a, tc.b, max, got, tc.want)
		}
	}
	if pocIsLater(1, 0, 0) {
		t.Error("pocIsLater with max 0 should be false")
	}
}
