#!/bin/bash
# tools/update_golden.sh
# Regenerate golden test bitstreams and update checksums.
#
# This script:
#   1. Runs gen_and_verify.sh to encode all test cases with ffmpeg+libx264
#      and verify byte-exact match between FFmpeg decode and hi264 decode
#   2. Copies only PASSING .264 files into testdata/golden/
#   3. Prints the Go map literal with SHA-256 hashes to paste into
#      pkg/decoder/decoder_test.go
#
# IMPORTANT: Only bitstreams that decode identically to FFmpeg are included.
# A test file is never added to golden unless gen_and_verify.sh confirms
# the hi264 output matches FFmpeg byte-for-byte.
#
# Prerequisites:
#   - FFmpeg with libx264 support
#   - Go toolchain
#
# Usage:
#   bash tools/update_golden.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GOLDEN="$ROOT_DIR/testdata/golden"
TMPDIR=/tmp/hi264_tests
H264DEC="$ROOT_DIR/hi264dec"

# Step 1: Generate and verify against FFmpeg
echo "=== Step 1: Running gen_and_verify.sh ==="
bash "$ROOT_DIR/tools/gen_and_verify.sh"
echo ""

# Step 2: Build decoder
echo "=== Step 2: Building hi264dec ==="
(cd "$ROOT_DIR" && go build -o "$H264DEC" ./cmd/hi264dec)

# Step 3: Copy passing .264 files and compute checksums
mkdir -p "$GOLDEN"
echo ""
echo "=== Step 3: Copying passing tests and computing checksums ==="
echo ""

count=0
echo "// Generated by tools/update_golden.sh — do not edit manually."
echo "var goldenTests = map[string]string{"
for f in "$TMPDIR"/*.264; do
    name=$(basename "$f" .264)
    ref="$TMPDIR/${name}_ref.yuv"
    go_yuv="$TMPDIR/${name}_go.yuv"
    # Only include tests that passed (ref == go)
    if cmp -s "$ref" "$go_yuv" 2>/dev/null; then
        cp "$f" "$GOLDEN/$name.264"
        hash=$(shasum -a 256 "$go_yuv" | cut -d' ' -f1)
        printf '\t%-24s "%s",\n' "\"$name\":" "$hash"
        count=$((count + 1))
    fi
done
echo "}"
echo ""
echo "=== Copied $count passing tests to $GOLDEN ==="
echo "Paste the map above into pkg/decoder/decoder_test.go"
